-- Seed: Insert Dummy Categories Data
-- Description: Seeds the categories table with initial dummy data
-- Date: 2024
-- Note: This matches the hardcoded categories in frontend/src/services/api.ts
-- Note: IDs are auto-generated by Supabase (uuid_generate_v4())
-- Note: For seeding, we use external URLs. For production, images should be uploaded to Supabase Storage.

-- Clear existing data (optional - comment out if you want to keep existing data)
-- TRUNCATE TABLE categories CASCADE;

-- Insert dummy categories
-- IDs are auto-generated by the database (DEFAULT uuid_generate_v4())
INSERT INTO categories (name, slug, image_url) VALUES
  ('T-Shirts', 't-shirts', 'https://images.unsplash.com/photo-1622445275463-afa2ab738c34?q=80&w=987&auto=format&fit=crop'),
  ('Hoodies', 'hoodies', 'https://images.unsplash.com/photo-1606136214376-372e3a1a6f8b?q=80&w=987&auto=format&fit=crop'),
  ('Mugs', 'mugs', 'https://images.unsplash.com/photo-1541167760496-1628856ab772?q=80&w=1037&auto=format&fit=crop'),
  ('Wall Art', 'wall-art', 'https://images.unsplash.com/photo-1590945199859-676b6b7e8d2e?q=80&w=1015&auto=format&fit=crop'),
  ('Accessories', 'accessories', 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?q=80&w=880&auto=format&fit=crop'),
  ('Jackets', 'jackets', 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1170&auto=format&fit=crop'),
  ('Pants', 'pants', 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?q=80&w=1167&auto=format&fit=crop'),
  ('Shoes', 'shoes', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1170&auto=format&fit=crop')
ON CONFLICT (slug) DO NOTHING;

-- Verify the data
SELECT id, name, slug, image_url, created_at 
FROM categories 
ORDER BY name;

